
package net.tecgurus.clienteservice._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "clienteServicePortType", targetNamespace = "http://www.tecgurus.net/clienteService/1.0")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteServicePortType {


    /**
     * 
     * @param reqCteData
     * @return
     *     returns net.tecgurus.clienteservice._1.RespCteData
     */
    @WebMethod(action = "http://www.tecgurus.net/clienteService/listarClientesOperation")
    @WebResult(name = "resp_cte_data", targetNamespace = "http://www.tecgurus.net/clienteService/1.0", partName = "resp_cte_data")
    public RespCteData listarClientesOperation(
        @WebParam(name = "req_cte_data", targetNamespace = "http://www.tecgurus.net/clienteService/1.0", partName = "req_cte_data")
        ReqCteData reqCteData);

}
